
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Serendevity
subtitle: "software development done right!"
url: "https://www.serendevity.com"
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/serendevity.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: lorem
    desc: "Just some placeholder posts, lorem ipsum and the rest."
